[package]
name = "gd32vf103-hal"
version = "0.0.1"
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/luojia65/gd32vf103-hal"
description = "Hardware abstract layer (HAL) for RISC-V microcontroller GD32VF103"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"
license-file = "LICENSE-MULAN"
keywords = ["riscv", "gd32v", "hal", "embedded-hal"]
build = "build.rs"

[dependencies]
gd32vf103-pac = "0.2"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
nb = "0.1"
riscv = "0.5"

[dependencies.void]
default-features = false
version = "1.0.2"

[dev-dependencies]
panic-halt = "*"
riscv-rt = "*"
linked_list_allocator = "*"

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true

[lib]
name = "gd32vf103_hal"
test = false
bench = false
